# Vancouver Housing Data 2025 ‚Äì Part 1: Data Cleaning and Structuring

This notebook prepares the datasets for the Vancouver Housing Affordability and Urban Risk project.  
It focuses on data wrangling, merging, and indicator generation to enable meaningful analysis across municipalities.

---

## 1. Project Summary and Dataset Overview

Assess housing infrastructure conditions and regional disparities across Metro Vancouver by analyzing the age of owner-occupied dwellings and median household income.   

---

### Part 1 Objectives


- Import and preview key datasets
- Clean and standardize tables (e.g., column names, data types)
- Merge housing and income data by jurisdiction
- Output a dataset ready for visual and statistical analysis

---

### Data Sources

**Table 3.1.2** Owner-Occupied Units by Construction Period (Metro Vancouver) 
**Table 1.5.1** Median Household Income by Jurisdiction (2021 Census)

Data Source:
The datasets used in this project were retrieved from:
[Metro Vancouver Housing Data Book 2025](https://metrovancouver.org/services/regional-planning/housing-data-book),  
available through the Metro Vancouver Regional Planning Division.

---
### Final Output
A single, unified dataset that supports descriptive analysis, clustering, and PCA.

## 2. Load and Clean Each Table

In this section, we load and clean the two primary datasets used in the project. Each table is processed separately to ensure data consistency, remove irrelevant rows, and prepare key indicators such as housing age and median household income by jurisdiction.

In [3]:
# Import libraries
import pandas as pd
import requests
from io import BytesIO

### 2.1 Load and Clean Housing Table (Table 3.1.2)

#### Load Housing Data from Metro Vancouver

This block attempts to fetch the housing Excel file directly from the [Metro Vancouver Housing Data Book 2025](https://metrovancouver.org/services/regional-planning/housing-data-book).  
It targets **Part 3 ‚Äì Ownership Housing**, which contains construction year details for owner-occupied dwellings.

If the internet download fails (due to access restrictions or redirects), the script will automatically fall back to a locally saved copy of the file.

- üîó **Online source:** `metro-vancouver-housing-data-book-2025-part-3-ownership-housing.xlsx`
- üìÑ **Target sheet:** `"Table 3.1.2"` ‚Äì Owner-Occupied Dwellings by Period Built

In [6]:
# Define URL and sheet name
url = "https://metrovancouver.org/services/regional-planning/Documents/metro-vancouver-housing-data-book-2025-part-3-ownership-housing.xlsx"
sheet_name = "Table 3.1.2"

try:
    print("üì° Attempting to download data from Metro Vancouver...")
    response = requests.get(url)
    excel_file = BytesIO(response.content)
    xls = pd.ExcelFile(excel_file)
    print("‚úÖ File successfully loaded from the internet.")
except Exception as e:
    print("‚ö†Ô∏è Could not retrieve file online. Trying local file instead.")
    xls = pd.ExcelFile("ownership_housing.xlsx")

# Load selected sheet
table_312 = pd.read_excel(xls, sheet_name=sheet_name, skiprows=0)
table_312.head(10)

üì° Attempting to download data from Metro Vancouver...
‚ö†Ô∏è Could not retrieve file online. Trying local file instead.

,metrovancouver | Housing Data Book 2025 | Part 3 - Ownership Housing,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Table 3.1.2. Owner-Occupied Dwelling Units by ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MEMBER JURISDICTION,Total Owner-Occupied,2016 to 2021,NaN,2011 to 2015,NaN,2001 to 2010,NaN,1991 to 2000,NaN,1981 to 1990,NaN,1971 to 1980,NaN,1961 to 1970,NaN,Pre-1961,NaN
3,NaN,#,#,%,#,%,#,%,#,%,#,%,#,%,#,%,#,%
4,Anmore,675,60,0.088889,100,0.148148,200,0.296296,180,0.266667,60,0.088889,30,0.044444,15,0.022222,20,0.02963
5,Belcarra,230,10,0.043478,0,0,30,0.130435,45,0.195652,45,0.195652,65,0.282609,30,0.130435,0,0
6,Bowen Island,1465,145,0.098976,105,0.071672,220,0.150171,250,0.170648,215,0.146758,265,0.180887,95,0.064846,175,0.119454
7,Burnaby,61185,7110,0.116205,5385,0.088012,11110,0.18158,10020,0.163766,8505,0.139005,8145,0.133121,3920,0.064068,6985,0.114162
8,Coquitlam,38795,4275,0.110195,4245,0.109421,4105,0.105813,8625,0.222322,6990,0.180178,4300,0.110839,3960,0.102075,2295,0.059157
9,Delta,28785,2015,0.070002,1260,0.043773,1870,0.064964,3370,0.117075,4760,0.165364,8540,0.296682,5045,0.175265,1920,0.066701

In [7]:
table_312.tail(10)

,metrovancouver | Housing Data Book 2025 | Part 3 - Ownership Housing,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
21,Richmond,57800,6000,0.103806,5425,0.093858,10040,0.173702,12330,0.213322,9655,0.167042,10125,0.175173,2530,0.043772,1685,0.029152
22,Surrey,129100,13705,0.106158,13415,0.103912,29470,0.228273,27475,0.21282,23670,0.183346,12515,0.09694,4200,0.032533,4650,0.036019
23,Tsawwassen First Nation,715,390,0.545455,45,0.062937,25,0.034965,120,0.167832,95,0.132867,20,0.027972,0,0,10,0.013986
24,Vancouver,138850,12035,0.086676,10765,0.07753,21915,0.157832,27400,0.197335,18015,0.129744,14350,0.103349,6345,0.045697,28025,0.201837
25,West Vancouver,12540,765,0.061005,665,0.05303,1425,0.113636,1545,0.123206,1925,0.153509,1505,0.120016,2015,0.160686,2705,0.21571
26,White Rock,6960,595,0.085489,560,0.08046,855,0.122845,1280,0.183908,1495,0.214799,1290,0.185345,420,0.060345,465,0.06681
27,METRO VANCOUVER,647870,62800,0.096933,55410,0.085526,108745,0.16785,125720,0.194051,101555,0.156752,86785,0.133954,40825,0.063014,66015,0.101895
28,"Source: Statistics Canada, 2021 Census of Popu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Note: Values may not add up to 100% of Metro V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,n/a: not available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Set row 2 as the header and recreate the DataFrame
table_312.columns = table_312.iloc[2]
table_312 = table_312.iloc[4:].reset_index(drop=True)
table_312.head(10)

2,MEMBER JURISDICTION,Total Owner-Occupied,2016 to 2021,NaN,2011 to 2015,NaN,2001 to 2010,NaN,1991 to 2000,NaN,1981 to 1990,NaN,1971 to 1980,NaN,1961 to 1970,NaN,Pre-1961,NaN
0,Anmore,675,60,0.088889,100,0.148148,200,0.296296,180,0.266667,60,0.088889,30,0.044444,15,0.022222,20,0.02963
1,Belcarra,230,10,0.043478,0,0,30,0.130435,45,0.195652,45,0.195652,65,0.282609,30,0.130435,0,0
2,Bowen Island,1465,145,0.098976,105,0.071672,220,0.150171,250,0.170648,215,0.146758,265,0.180887,95,0.064846,175,0.119454
3,Burnaby,61185,7110,0.116205,5385,0.088012,11110,0.18158,10020,0.163766,8505,0.139005,8145,0.133121,3920,0.064068,6985,0.114162
4,Coquitlam,38795,4275,0.110195,4245,0.109421,4105,0.105813,8625,0.222322,6990,0.180178,4300,0.110839,3960,0.102075,2295,0.059157
5,Delta,28785,2015,0.070002,1260,0.043773,1870,0.064964,3370,0.117075,4760,0.165364,8540,0.296682,5045,0.175265,1920,0.066701
6,Electoral Area A,3280,495,0.150915,495,0.150915,1205,0.367378,740,0.22561,45,0.01372,50,0.015244,10,0.003049,220,0.067073
7,Langley City,7920,475,0.059975,410,0.051768,880,0.111111,2125,0.268308,1350,0.170455,2115,0.267045,385,0.048611,170,0.021465
8,Langley Township,38430,4905,0.127635,4175,0.108639,6655,0.173172,7765,0.202056,6300,0.163934,6145,0.159901,1340,0.034869,1135,0.029534
9,Lions Bay,445,10,0.022472,0,0,25,0.05618,30,0.067416,90,0.202247,225,0.505618,55,0.123596,0,0

In [9]:
#Remove percentage columns
'''
Step 1: Identify columns that are NaN (likely percent columns)
'''
columns_to_remove = [col for col in table_312.columns if pd.isna(col)]
'''
# Step 3: Drop those columns from the DataFrame
'''
table_312 = table_312.drop(columns=columns_to_remove)

# Rename columns

table_312.columns = [
    'jurisdiction',
    'total_owner_occupied',
    'built_2016_2021',
    'built_2011_2015',
    'built_2001_2010',
    'built_1991_2000',
    'built_1981_1990',
    'built_1971_1980',
    'built_1961_1970',
    'built_pre_1961'
]

table_312.head()

,jurisdiction,total_owner_occupied,built_2016_2021,built_2011_2015,built_2001_2010,built_1991_2000,built_1981_1990,built_1971_1980,built_1961_1970,built_pre_1961
0,Anmore,675,60,100,200,180,60,30,15,20
1,Belcarra,230,10,0,30,45,45,65,30,0
2,Bowen Island,1465,145,105,220,250,215,265,95,175
3,Burnaby,61185,7110,5385,11110,10020,8505,8145,3920,6985
4,Coquitlam,38795,4275,4245,4105,8625,6990,4300,3960,2295

In [10]:
# Remove the summary row for "METRO VANCOUVER" to focus only on individual jurisdictions
table_312 = table_312[table_312['jurisdiction'].str.upper() != 'METRO VANCOUVER']

# Drop any rows where 'total_owner_occupied' is missing (likely notes or footers)
table_312 = table_312.dropna(subset=['total_owner_occupied'])

In [11]:
table_312.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 22
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jurisdiction          23 non-null     object
 1   total_owner_occupied  23 non-null     object
 2   built_2016_2021       23 non-null     object
 3   built_2011_2015       23 non-null     object
 4   built_2001_2010       23 non-null     object
 5   built_1991_2000       23 non-null     object
 6   built_1981_1990       23 non-null     object
 7   built_1971_1980       23 non-null     object
 8   built_1961_1970       23 non-null     object
 9   built_pre_1961        23 non-null     object
dtypes: object(10)
memory usage: 2.0+ KB

In [12]:
# Convert all columns (except 'jurisdiction') to numeric
cols_to_convert = table_312.columns.drop('jurisdiction')
table_312[cols_to_convert] = table_312[cols_to_convert].apply(pd.to_numeric, errors='coerce')

In [13]:
table_312.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 22
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jurisdiction          23 non-null     object
 1   total_owner_occupied  23 non-null     int64
 2   built_2016_2021       23 non-null     int64
 3   built_2011_2015       23 non-null     int64
 4   built_2001_2010       23 non-null     int64
 5   built_1991_2000       23 non-null     int64
 6   built_1981_1990       23 non-null     int64
 7   built_1971_1980       23 non-null     int64
 8   built_1961_1970       23 non-null     int64
 9   built_pre_1961        23 non-null     int64
dtypes: int64(9), object(1)
memory usage: 2.0+ KB

### 2.2 Load and Clean Income Table (Table 1.5.1)

#### Load Income Data from Metro Vancouver

This block loads the **Income Data** from the [Metro Vancouver Housing Data Book 2025](https://metrovancouver.org/services/regional-planning/housing-data-book).  
It targets the Excel file from **Part 3 ‚Äì Ownership Housing**, which includes income metrics by jurisdiction.

The script first attempts to download the data from the official online source.  
If the internet request fails, it automatically falls back to a locally saved version of the file.

- üîó **Online source:** `metro-vancouver-housing-data-book-part-3-data-tables.xlsx`
- üìÑ **Target sheet (later defined):** `"Table 1.5.1"` ‚Äì Median Household Incomes by Jurisdiction (2021 Census)

In [16]:
# Define URL and sheet name for Income Data
url_income = "https://metrovancouver.org/_layouts/download.aspx?SourceUrl=https://metrovancouver.org/services/regional-planning/Documents/metro-vancouver-housing-data-book-part-1-data-tables.xlsx"
sheet_name_income = "Table 1.5.1"

try:
    print("üí∏ Attempting to download income data from Metro Vancouver...")
    response = requests.get(url_income)
    excel_file = BytesIO(response.content)
    xls_income = pd.ExcelFile(excel_file)
    print("‚úÖ Income file successfully loaded from the internet.")
    
except Exception as e:
    print("‚ö†Ô∏è Could not retrieve file online. Trying local file instead.")
    xls_income = pd.ExcelFile("ownership_housing.xlsx")

# Load selected sheet
table_151 = pd.read_excel(xls_income, sheet_name=sheet_name_income, skiprows=0)
table_151.head(10)

üí∏ Attempting to download income data from Metro Vancouver...
‚úÖ Income file successfully loaded from the internet.

,metrovancouver | Housing Data Book 2025 | Part 1 - Household Profile,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Table 1.5.1. Median Household Incomes, Metro V...",NaN,NaN,NaN,NaN,NaN,NaN
2,MEMBER JURISDICTION,2015,NaN,2020,NaN,2015 to 2020 % change\n(inflation adjusted),NaN
3,NaN,Total Median Household Income\n(2020 Constant ...,After-Tax Median Household Income\n(2020 Const...,Total Median Household Income\n(2020 Constant ...,After-Tax Median Household Income\n(2020 Const...,Total Median Household Income,After-Tax Median Household Income
4,Anmore,151000,123000,162000,136000,0.072848,0.105691
5,Belcarra,139000,114000,168000,138000,0.208633,0.210526
6,Bowen Island,97000,83000,111000,95000,0.14433,0.144578
7,Burnaby,70000,61600,83000,73500,0.185714,0.193182
8,Coquitlam,80000,70500,92000,82000,0.15,0.163121
9,Delta,100000,86000,108000,95000,0.08,0.104651

In [17]:
table_151.tail(10)

,metrovancouver | Housing Data Book 2025 | Part 1 - Household Profile,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
19,Port Coquitlam,91000,78500,102000,89000,0.120879,0.133758
20,Port Moody,101000,85000,115000,99000,0.138614,0.164706
21,Richmond,70500,62400,79000,71000,0.120567,0.137821
22,Surrey,84000,73500,98000,87000,0.166667,0.183673
23,Tsawwassen First Nation,91000,81000,98000,86000,0.076923,0.061728
24,Vancouver,70500,61600,82000,72000,0.163121,0.168831
25,West Vancouver,97000,83000,104000,90000,0.072165,0.084337
26,White Rock,67500,58400,73000,65000,0.081481,0.113014
27,METRO VANCOUVER,78500,68500,90000,79500,0.146497,0.160584
28,"Source: Statistics Canada, 2021 Census of Popu...",NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Set row 2 as the header and recreate the DataFrame
table_151.columns = table_151.iloc[2]
table_151 = table_151.iloc[4:].reset_index(drop=True)
table_151.head(10)

2,MEMBER JURISDICTION,2015,NaN,2020,NaN,2015 to 2020 % change\n(inflation adjusted),NaN
0,Anmore,151000,123000,162000,136000,0.072848,0.105691
1,Belcarra,139000,114000,168000,138000,0.208633,0.210526
2,Bowen Island,97000,83000,111000,95000,0.14433,0.144578
3,Burnaby,70000,61600,83000,73500,0.185714,0.193182
4,Coquitlam,80000,70500,92000,82000,0.15,0.163121
5,Delta,100000,86000,108000,95000,0.08,0.104651
6,Electoral Area A,50000,45600,63600,58000,0.272,0.27193
7,Langley City,64500,56400,77000,69000,0.193798,0.223404
8,Langley Township,98000,84000,108000,94000,0.102041,0.119048
9,Lions Bay,135000,112000,140000,121000,0.037037,0.080357

In [19]:
# Rename columns with clear, unique names
table_151.columns = [
    "jurisdiction",
    "income_2015_total",
    "income_2015_after_tax",
    "income_2020_total",
    "income_2020_after_tax",
    "change_total_2015_2020",
    "change_after_tax_2015_2020"
]

In [20]:
table_151.tail(10)

,jurisdiction,income_2015_total,income_2015_after_tax,income_2020_total,income_2020_after_tax,change_total_2015_2020,change_after_tax_2015_2020
15,Port Coquitlam,91000,78500,102000,89000,0.120879,0.133758
16,Port Moody,101000,85000,115000,99000,0.138614,0.164706
17,Richmond,70500,62400,79000,71000,0.120567,0.137821
18,Surrey,84000,73500,98000,87000,0.166667,0.183673
19,Tsawwassen First Nation,91000,81000,98000,86000,0.076923,0.061728
20,Vancouver,70500,61600,82000,72000,0.163121,0.168831
21,West Vancouver,97000,83000,104000,90000,0.072165,0.084337
22,White Rock,67500,58400,73000,65000,0.081481,0.113014
23,METRO VANCOUVER,78500,68500,90000,79500,0.146497,0.160584
24,"Source: Statistics Canada, 2021 Census of Popu...",NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Drop the last two rows
table_151 = table_151.iloc[:-2].reset_index(drop=True)

# Preview the cleaned table
table_151.tail()

,jurisdiction,income_2015_total,income_2015_after_tax,income_2020_total,income_2020_after_tax,change_total_2015_2020,change_after_tax_2015_2020
18,Surrey,84000,73500,98000,87000,0.166667,0.183673
19,Tsawwassen First Nation,91000,81000,98000,86000,0.076923,0.061728
20,Vancouver,70500,61600,82000,72000,0.163121,0.168831
21,West Vancouver,97000,83000,104000,90000,0.072165,0.084337
22,White Rock,67500,58400,73000,65000,0.081481,0.113014

In [22]:
table_151.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   jurisdiction                23 non-null     object
 1   income_2015_total           23 non-null     object
 2   income_2015_after_tax       23 non-null     object
 3   income_2020_total           23 non-null     object
 4   income_2020_after_tax       23 non-null     object
 5   change_total_2015_2020      23 non-null     object
 6   change_after_tax_2015_2020  23 non-null     object
dtypes: object(7)
memory usage: 1.4+ KB

In [23]:
# Convert all columns (except 'jurisdiction') to numeric
cols_to_convert = table_151.columns.drop('jurisdiction')
table_151[cols_to_convert] = table_151[cols_to_convert].apply(pd.to_numeric, errors='coerce')

In [24]:
table_151.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   jurisdiction                23 non-null     object
 1   income_2015_total           23 non-null     int64
 2   income_2015_after_tax       23 non-null     int64
 3   income_2020_total           23 non-null     int64
 4   income_2020_after_tax       23 non-null     int64
 5   change_total_2015_2020      23 non-null     float64
 6   change_after_tax_2015_2020  23 non-null     float64
dtypes: float64(2), int64(4), object(1)
memory usage: 1.4+ KB

## 3. Merge Tables

In this section, we combine the cleaned housing and income datasets using the jurisdiction column.

In [26]:
# Step 1: Standardize key column names
table_312.rename(columns={"jurisdiction": "jurisdiction"}, inplace=True)
table_151.rename(columns={"jurisdiction": "jurisdiction"}, inplace=True)

# Step 2: Merge tables based on jurisdiction name
merged_table = pd.merge(
    table_312, 
    table_151, 
    on="jurisdiction", 
    how="inner"
)

# Step 3: Preview merged result
merged_table.head()

,jurisdiction,total_owner_occupied,built_2016_2021,built_2011_2015,built_2001_2010,built_1991_2000,built_1981_1990,built_1971_1980,built_1961_1970,built_pre_1961,income_2015_total,income_2015_after_tax,income_2020_total,income_2020_after_tax,change_total_2015_2020,change_after_tax_2015_2020
0,Anmore,675,60,100,200,180,60,30,15,20,151000,123000,162000,136000,0.072848,0.105691
1,Belcarra,230,10,0,30,45,45,65,30,0,139000,114000,168000,138000,0.208633,0.210526
2,Bowen Island,1465,145,105,220,250,215,265,95,175,97000,83000,111000,95000,0.144330,0.144578
3,Burnaby,61185,7110,5385,11110,10020,8505,8145,3920,6985,70000,61600,83000,73500,0.185714,0.193182
4,Coquitlam,38795,4275,4245,4105,8625,6990,4300,3960,2295,80000,70500,92000,82000,0.150000,0.163121

## 4. Save Clean Dataset

In this section, the final step, we export the merged and cleaned dataset for future use. This file will serve as the input for the descriptive and multivariate analyses conducted in the following notebooks.

To facilitate reuse in future notebooks, we export the cleaned and merged dataset in `.pkl` (Pickle) format.  
Pickle is a native Python format that preserves data types and structure, allowing for faster and more efficient loading compared to `.csv`.  
This makes it ideal for development workflows where performance and consistency are priorities.

- Format: `.pkl` (binary, Python-native)
- Ready to be loaded in: `Vancouver_Housing_part2.ipynb`

In [28]:
# Save merged DataFrame as a Pickle file
merged_table.to_pickle("merged_housing_income_data.pkl")
print("‚úÖ Pickle file saved successfully.")

‚úÖ Pickle file saved successfully.

---
## 5. Summary

In this first notebook, we prepared the datasets that will serve as the foundation for our housing risk and regional disparity analysis. The steps included:

- **Loading** two key datasets from the Metro Vancouver Housing Data Book:
  - Table 3.1.2: Owner-Occupied Dwellings by Year Built
  - Table 1.5.1: Median Household Income by Jurisdiction (2021)

- **Cleaning** each dataset individually:
  - Removed metadata rows and redefined headers
  - Renamed columns for clarity
  - Dropped non-jurisdiction rows (e.g., region totals and notes)

- **Merging** both datasets on the `jurisdiction` column to create a unified view by municipality

- **Exporting** the final cleaned dataset as a `.pkl` file for efficient reuse in upcoming analyses

This prepared file will now be used in **Notebook 2** to generate descriptive insights and regional comparisons.